# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-01 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeopleRating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
