# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-02 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PeopleRating', '0003_auto_20170102_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='rating',
            new_name='stars',
        ),
        migrations.AddField(
            model_name='rating',
            name='name',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='PeopleRating.Person'),
            preserve_default=False,
        ),
    ]
