# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-02 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeopleRating', '0004_auto_20170102_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='stars',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=4),
        ),
    ]
